# Workflow name
name: Deploy Docs

# Controls when the action will run.
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Install dependencies (does not create .lock file) and install only production dependencies
      - name: Install Dependencies
        run: npm ci

      - name: Build documentation
        run: npm run build
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ vars.TURBO_TEAM }}

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: touch storybook-static/.nojekyll && npm run deploy-storybook -- --ci --existing-output-dir=./storybook-static
        env:
          # To ensure that when this step runs, we authenticate 
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

      - name: Print URL
        run: echo "$(gh api repos/${{ github.repository.owner }}/${{ github.repository }}/pages --jq '.html_url')"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}